all: stb gl_loader

stb:
	curl -o stb_image.h https://raw.githubusercontent.com/nothings/stb/master/stb_image.h

gl_loader:
	curl -L -o loader.zip https://github.com/BeratDizdar/miniglcorearb/archive/refs/heads/main.zip
	tar -xf loader.zip
	rm loader.zip